version: "1.0"

volumes:
  db-app:

services:
  web:
    build: .
    container_name: photoshare_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db-app:5432/postgres
      - JWT_SECRET_KEY=XGMncy8pQzhh0PQTluPhkSweCm9scGEH3nZUeqkpmi8
    depends_on:
      - db-app
    networks:
      - app-network

  db-app:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-app:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
